### ISSUE TITLE
`om init` - for smart template generation

### ISSUE THREAD

**Issue by srid** [juspay/omnix#152]
Add

```
om init
```    

This should support a registry of flake templates (use our various `flake-parts` modules), initialize them using `nix flake init` as well as fill in any user-specific content using the `templateGenerators` idea in [flake-parts/templates#7 (comment)](https://github.com/flake-parts/templates/issues/7#issuecomment-2160581489)

The goal is to have `om init` create flakes for any kind of stack, eventually.

## Implementation

To extend `flake.templates`, we can add:

```nix
{
  flake.templateGenerators.default = {
    # The generator to use (string or package)
    generator = "om init";
    # Arbitrary metaata (of the template) to pass to the generator.
    templates.default.params = {
    };
  };
}
```

Here, `generator` can be an arbitrary derivation (a function that takes `pkgs` and returns a `types.package`?) *or* it can be a string that represents the command line to use to invoke the generator? `om init` can fetch templates, and look for the special `"om init"` generator, in which case it can short-circuit by calling the necessary internal initializer function, passing the `templates.?.params` property as necessary.

## Tasks

- [x] #167 
- [x] #168
- [x] #169
- [x] #171
- [x] Implement CLI test: #173
- [ ] template config: Upstream now or later?
  - [ ] Finalize the spec
- [x] registry: Avoid `flake.lock` explosion, by switching to a JSON registry? #190
- [ ] ...

**Comment by srid** [comment]
cc @roberth (have I understood your `templateGenerators` idea?)

**Comment by srid** [comment]
Alternative, if we don't care about being general enough, we could just pass `om` configuration for templates as:

```nix
{
  templates.default = { ... };
  om.templates.default = {
    params = {
      # ...
    };
  };
}
```

This way, we don't have to fully spec out the general case first.

(Later, if a general spec does emerge, it should be straightforward to port the `om.templates` configuration to it).

**Comment by srid** [comment]
<img width="257" alt="image" src="https://github.com/user-attachments/assets/b8f92468-2df7-4190-847b-6047354a0c72">

Regarding this, for MVP - let's keep the additional config *in this repo*, so it gives us some leeway to change things in future. Otherwise, we can consider this feature basically done.
