### ISSUE TITLE
`om develop`: Nix devShell that automates more and guides the user

### ISSUE THREAD

**Issue by srid** [juspay/omnix#316]
## Motivation

The user `git clone`s some project. What to do next?

## Mechanism

Generally speaking, 3 things need to happen:

1. Setup the necessary Nix caches to avoid compiling locally
    - Notably, one might use a private Cachix cache. Suppose the read-only auth token is stored in the Git repo, we want to run both  `cachix authtoken ...` and `cachix use ...`
1. Run `om health`, which checks various things including that cachix cache are in use (we may need #315), and instruct users to fix the problems accordingly (cf. #291)
3. Show "next steps", which varies between projects, but typically involves running `direnv allow` (or `nix develop`) as first step, followed by VSCode setup. This can be Markdown we render in the terminal.

## Questions

(3) can be part of `om show`, but the whole 1-2-3 step process may well require a new subcommand?

## Roadmap

- [x] #319
- [x] #329
- [x] Refactor: health check cum auto resolution (so combining `om health` cachix with our cachix-use action)
  - [x] #328 
  - [x] Auto resolution of health check failure (esp. for cachix) #330
- [x] Test: Cachix
  - [x] Fix: use staticWhich to locate cachix #331
- [x] Test: `om health`
- [x] `om hack --direnv` for using in `.envrc`
- [x] General logging/output improvements
  - Avoid nix command dumps
  - Info like `cachix up` running should still be show. Should we make nix command dump debug level permanently? 
- [ ] Non-direnv mode: Simply running `om hack` should either put the user on `nix develop` shell (sans direnv) or instruct them how to get direnv (if the project requires it)

**Comment by srid** [comment]
This seems to be the better markdown renderer:

https://github.com/swsnr/mdcat

Takes a bunch of setting up, however:

<img width="677" alt="image" src="https://github.com/user-attachments/assets/e65ff68d-53be-4426-96c9-d5175db406ee">


Result:

<img width="627" alt="image" src="https://github.com/user-attachments/assets/15f80b22-fdee-4ae0-8a06-97f24f050f32">


Surprisingly, those links are clickable by default - hover over (they get underlined) and click. Not even need to press modifier keys like <kbd>Cmd</kbd>.

<img width="330" alt="image" src="https://github.com/user-attachments/assets/a0b96bc9-a332-48ff-a106-ce34e1d76067">

**Comment by srid** [comment]
We actually don't strictly need to do cachix part in `om hack`, because it can done outside of it.

`cachix use` is obviated by `flake.nix:nixConfig`:

<img width="293" alt="image" src="https://github.com/user-attachments/assets/99e8a276-243f-4bdc-93d3-99b258b8b413">

which we can activate in omnixrc:

<img width="292" alt="image" src="https://github.com/user-attachments/assets/de7db22a-f135-49d6-8be6-f5e739eb2ef3">

This leaves us with `cachix authtoken ...`, but that too can be added to the user's `.envrc`.

**Comment by srid** [comment]
Cachix configuration is now being piggybacked on `om health` config, and `om hack` now tries to "auto resolve" failures, by automatically running `cachix use`. The authtoken can be passed as env var, thus omnix doesn't have to handle it.

**Comment by srid** [comment]
https://omnix.page/om/develop.html
